/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uisemantics.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.ecview.semantic.uisemantics.UxValidatorProperty;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uisemantics.UxAvailableValidatorProperties}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UxAvailableValidatorPropertiesValidator {
	boolean validate();

	boolean validateProperties(EList<UxValidatorProperty> value);
}
