/**
 * Copyright (c) 2011 - 2015, Lunifera GmbH (Gross Enzersdorf), Loetz KG (Heidelberg)
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *         Florian Pirchner - Initial implementation
 */
package org.lunifera.ecview.semantic.uisemantics.validation;

import org.lunifera.ecview.semantic.uisemantics.UxAvailableBindings;
import org.lunifera.ecview.semantic.uisemantics.UxAvailableValidatorProperties;
import org.lunifera.ecview.semantic.uisemantics.UxAvailableVisibilityOptions;
import org.lunifera.ecview.semantic.uisemantics.UxElementURI;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uisemantics.UxElementDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UxElementDefinitionValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateUri(UxElementURI value);
	boolean validateBindingContainer(UxAvailableBindings value);
	boolean validateVisibilityContainer(UxAvailableVisibilityOptions value);
	boolean validateValidatorContainer(UxAvailableValidatorProperties value);
}
