/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uisemantics.validation;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uisemantics.UxEndpointDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UxEndpointDefValidator {
	boolean validate();

	boolean validateFinal(boolean value);
	boolean validateName(String value);
	boolean validateJvmType(JvmTypeReference value);
	boolean validateListbinding(boolean value);
}
