/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uisemantics.validation;

import org.lunifera.ecview.semantic.uisemantics.UxEPackageImport;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uisemantics.XImportDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XImportDeclarationValidator {
	boolean validate();

	boolean validateImportedEPackage(UxEPackageImport value);
}
