/*
 * generated by Xtext
 */
package org.lunifera.ecview.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UIGrammarUiModule extends org.lunifera.ecview.dsl.ui.AbstractUIGrammarUiModule {
	public UIGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
