<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uimodel" nsURI="http://www.lunifera.org/ecview/dsl/UIModel/core"
    nsPrefix="uimodel">
  <eClassifiers xsi:type="ecore:EClass" name="UiModel" eSuperTypes="#//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" upperBound="-1"
        eType="#//UiRootElements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiView" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YView #//UiRootElements #//UiModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiIDEView" eSuperTypes="#//UiView #//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//UiBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEndpointAlias" upperBound="-1"
        eType="#//UiBindingEndpointAlias" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiPoint" eSuperTypes="#//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBindingEndpointAlias" eSuperTypes="#//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" lowerBound="1"
        eType="#//UiBindingEndpointDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBindingEndpointDef" eSuperTypes="#//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindable" eType="ecore:EClass ../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" eType="ecore:EClass ../../org.lunifera.ecview.semantic.uisemantics/model/UISemanticsGrammar.ecore#//UxEndpointDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//UiPathSegment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBinding" eSuperTypes="#//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//UiBindingEndpointDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAlias" eType="#//UiBindingEndpointAlias"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetToSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceToTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//UiBindingEndpointDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAlias" eType="#//UiBindingEndpointAlias"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiPathSegment" eSuperTypes="#//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jvmField" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//UiPathSegment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBeanSlot" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YBeanSlot #//UiModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jvmType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiViewSet" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YViewSet #//UiRootElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEndpointAlias" upperBound="-1"
        eType="#//UiBindingEndpointAlias" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiRootElements" abstract="true" interface="true"
      eSuperTypes="#//UiModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiModelElement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiMaxLengthValidator" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/validation.ecore#//YMaxLengthValidator #//UiModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiMinLengthValidator" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/validation.ecore#//YMinLengthValidator #//UiModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiRegexpValidator" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/validation.ecore#//YRegexpValidator #//UiModelElement"/>
</ecore:EPackage>
