<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uiextension" nsURI="http://www.lunifera.org/ecview/dsl/UIModel/extension"
    nsPrefix="uiextension">
  <eClassifiers xsi:type="ecore:EClass" name="UiGridLayoutAssigment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass ../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YEmbeddable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="ecore:EEnum ../../org.eclipse.emf.ecp.ecview.extension.model/model/extension.ecore#//YAlignment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="ecore:EClass UIGrammarCore.ecore#//UiPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass UIGrammarCore.ecore#//UiPoint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiGridLayout" eSuperTypes="../../org.eclipse.emf.ecp.ecview.extension.model/model/extension.ecore#//YGridLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//UiGridLayoutAssigment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiTextField" eSuperTypes="../../org.eclipse.emf.ecp.ecview.extension.model/model/extension.ecore#//YTextField"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiList" eSuperTypes="../../org.eclipse.emf.ecp.ecview.extension.model/model/extension.ecore#//YList"/>
</ecore:EPackage>
