<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uimodel" nsURI="http://www.lunifera.org/ecview/dsl/UIModel/core"
    nsPrefix="uimodel">
  <eClassifiers xsi:type="ecore:EClass" name="UiModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewSets" upperBound="-1"
        eType="#//UiViewSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//UiView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiView" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YView"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiIDEView" eSuperTypes="#//UiView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//UiBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEndpointAlias" upperBound="-1"
        eType="#//UiBindingEndpointAlias" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBindingEndpointAlias">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" lowerBound="1"
        eType="#//UiBindingEndpointDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBindingEndpointDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindable" eType="ecore:EClass ../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YBindable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" eType="ecore:EClass ../../org.lunifera.ecview.semantic.uisemantics/model/UISemanticsGrammar.ecore#//UxEndpointDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//UiPathSegment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//UiBindingEndpointDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAlias" eType="#//UiBindingEndpointAlias"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetToSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceToTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//UiBindingEndpointDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAlias" eType="#//UiBindingEndpointAlias"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiPathSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jvmField" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//UiPathSegment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiBeanSlot" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YBeanSlot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jvmType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiViewSet" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/core.ecore#//YViewSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEndpointAlias" upperBound="-1"
        eType="#//UiBindingEndpointAlias" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
