/**
 * generated by Xtext
 */
package org.lunifera.ecview.dsl.validation;

import org.lunifera.ecview.dsl.validation.AbstractUIGrammarValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class UIGrammarValidator extends AbstractUIGrammarValidator {
}
