/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uimodel.uiextension.validation;

import org.lunifera.ecview.semantic.uimodel.uiextension.UiVisibilityProcessor;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.uiextension.UiVisibilityProcessorAssignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiVisibilityProcessorAssignmentValidator {
	boolean validate();

	boolean validateProcessor(UiVisibilityProcessor value);
	boolean validateProcessorAlias(UiVisibilityProcessor value);
}
