/*
* generated by Xtext
*/
package org.lunifera.ecview.uisemantics.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.lunifera.ecview.uisemantics.services.UISemanticsGrammarGrammarAccess;

public class UISemanticsGrammarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UISemanticsGrammarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.lunifera.ecview.uisemantics.parser.antlr.internal.InternalUISemanticsGrammarParser createParser(XtextTokenStream stream) {
		return new org.lunifera.ecview.uisemantics.parser.antlr.internal.InternalUISemanticsGrammarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public UISemanticsGrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UISemanticsGrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
