/**
 * Copyright (c) 2011 - 2015, Lunifera GmbH (Gross Enzersdorf), Loetz KG (Heidelberg)
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *         Florian Pirchner - Initial implementation
 */
package org.lunifera.ecview.semantic.uimodel.validation;

import org.eclipse.xtext.common.types.JvmOperation;

import org.lunifera.ecview.semantic.uimodel.UiFlatAlignment;
import org.lunifera.ecview.semantic.uimodel.UiNestedProperty;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.UiColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiColumnValidator {
	boolean validate();

	boolean validateGetter(JvmOperation value);
	boolean validateIconName(String value);
	boolean validateVisible(boolean value);
	boolean validateOrderable(boolean value);
	boolean validateCollapsed(boolean value);
	boolean validateCollapsible(boolean value);
	boolean validateAlignment(UiFlatAlignment value);
	boolean validateExpandRatio(float value);

	boolean validateProperty(UiNestedProperty value);
}
