/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uimodel.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecp.ecview.common.model.core.YLayout;

import org.lunifera.ecview.semantic.uimodel.UiBinding;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.UiIDEView}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiIDEViewValidator {
	boolean validate();

	boolean validateLayouts(EList<YLayout> value);
	boolean validateBindings(EList<UiBinding> value);
}
