/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uimodel.validation;

import org.eclipse.emf.ecp.ecview.common.model.core.YBindable;

import org.lunifera.ecview.semantic.uimodel.UiPathSegment;

import org.lunifera.ecview.uisemantics.UxEndpointDef;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.UiSourceBindingEndpoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiSourceBindingEndpointValidator {
	boolean validate();

	boolean validateEmbeddable(YBindable value);
	boolean validateEndpoint(UxEndpointDef value);
	boolean validatePath(UiPathSegment value);
}
