/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uimodel.validation;

import org.lunifera.ecview.semantic.uimodel.UiField;
import org.lunifera.ecview.semantic.uimodel.UiValidatorAlias;
import org.lunifera.ecview.semantic.uimodel.UiValidatorDef;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.UiValidatorAssignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiValidatorAssignmentValidator {
	boolean validate();

	boolean validateField(UiField value);

	boolean validateValidatorDef(UiValidatorDef value);
	boolean validateValidatorAlias(UiValidatorAlias value);
}
