/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uimodel.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.ecview.semantic.uimodel.UiEmbeddable;
import org.lunifera.ecview.semantic.uimodel.UiValidatorAssignment;
import org.lunifera.ecview.semantic.uimodel.UiViewSet;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.UiView}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiViewValidator {
	boolean validate();

	boolean validateViewSet(UiViewSet value);
	boolean validateContent(UiEmbeddable value);
	boolean validateValidatorAssignments(EList<UiValidatorAssignment> value);
}
