/**
 *
 * $Id$
 */
package org.lunifera.ecview.semantic.uimodel.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.ecview.semantic.uimodel.UiBindingEndpointAlias;
import org.lunifera.ecview.semantic.uimodel.UiBindingExpression;
import org.lunifera.ecview.semantic.uimodel.UiChangeTrigger;
import org.lunifera.ecview.semantic.uimodel.UiVisibilityPropertiesAssignment;
import org.lunifera.ecview.semantic.uimodel.UiVisibilityRule;

/**
 * A sample validator interface for {@link org.lunifera.ecview.semantic.uimodel.UiVisibilityProcessor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UiVisibilityProcessorValidator {
	boolean validate();

	boolean validateDataUsed(EList<UiBindingEndpointAlias> value);

	boolean validateChangeTriggers(EList<UiChangeTrigger> value);

	boolean validateImportedElements(EList<UiBindingExpression> value);

	boolean validateBindingAlias(EList<UiBindingEndpointAlias> value);
	boolean validateChangeTrigger(EList<UiChangeTrigger> value);
	boolean validateRule(UiVisibilityRule value);
	boolean validatePropertiesAssignment(UiVisibilityPropertiesAssignment value);
}
