/**
 * generated by Xtext
 */
package org.lunifera.ecview.uisemantics.ui.contentassist;

import org.lunifera.ecview.uisemantics.ui.contentassist.AbstractUISemanticsGrammarProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class UISemanticsGrammarProposalProvider extends AbstractUISemanticsGrammarProposalProvider {
}
