/**
 * generated by Xtext
 */
package org.lunifera.ecview.dsl.ui.labeling;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class UIGrammarDescriptionLabelProvider /* implements org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider  */{
}
