/**
 * generated by Xtext
 */
package org.lunifera.ecview.dsl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class UIGrammarLabelProvider /* implements org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider  */{
  @Inject
  public UIGrammarLabelProvider(final AdapterFactoryLabelProvider delegate) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super is undefined for the type UIGrammarLabelProvider");
  }
}
