/*
* generated by Xtext
*/
package org.lunifera.ecview.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UIGrammarUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.lunifera.ecview.dsl.ui.internal.UIGrammarActivator.getInstance().getInjector("org.lunifera.ecview.dsl.UIGrammar");
	}
	
}
