/*
 * generated by Xtext
 */
package org.lunifera.ecview.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractUIGrammarValidator extends org.eclipse.xtext.xbase.validation.XbaseValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.lunifera.org/ecview/dsl/uimodel/core"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.lunifera.org/ecview/dsl/uimodel/extension"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://eclipse.org/emf/ecp/ecview/extension/view"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://eclipse.org/emf/ecp/ecview/core/view"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://eclipse.org/emf/ecp/ecview/core/validation"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/xtext/xbase/Xbase"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/xtext/common/JavaVMTypes"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/xtext/xbase/Xtype"));
		return result;
	}
}
