/**
 * generated by Xtext
 */
package org.lunifera.ecview.dsl.ui.quickfix;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class UIGrammarQuickfixProvider /* implements org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider  */{
}
