/*
* generated by Xtext
*/
package org.lunifera.ecview.uisemantics;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UISemanticsGrammarUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.lunifera.ecview.uisemantics.ui.internal.UISemanticsGrammarActivator.getInstance().getInjector("org.lunifera.ecview.uisemantics.UISemanticsGrammar");
	}
	
}
