/*
 * generated by Xtext
 */
package org.lunifera.ecview.uisemantics;

import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;
import org.lunifera.ecview.uisemantics.linking.UiSemanticsLinkingService;
import org.lunifera.ecview.uisemantics.naming.QualifiedNameProvider;
import org.lunifera.ecview.uisemantics.scoping.ScopeProvider;
import org.lunifera.ecview.uisemantics.scoping.UiImportedNamespaceAwareLocalScopeProvider;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class UISemanticsGrammarRuntimeModule extends
		org.lunifera.ecview.uisemantics.AbstractUISemanticsGrammarRuntimeModule {

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return QualifiedNameProvider.class;
	}

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return ScopeProvider.class;
	}

	@Override
	public Class<? extends XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
		return ScopeProvider.class;
	}

	@Override
	public void configureIScopeProviderDelegate(Binder binder) {
		binder.bind(IScopeProvider.class)
				.annotatedWith(
						Names.named("org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.delegate"))
				.to(UiImportedNamespaceAwareLocalScopeProvider.class);
	}

	public Class<? extends ILinkingService> bindILinkingService() {
		return UiSemanticsLinkingService.class;
	}

}
