/*
 * generated by Xtext
 */
package org.lunifera.ecview.uisemantics;

import org.lunifera.xtext.builder.xbase.setups.XbaseBundleSpaceStandaloneSetup;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
@SuppressWarnings("restriction")
public class UISemanticsGrammarBundleSpaceStandaloneSetup extends
		UISemanticsGrammarStandaloneSetup {

	public static void doSetup() {
		new UISemanticsGrammarBundleSpaceStandaloneSetup()
				.createInjectorAndDoEMFRegistration();
	}

	public Injector createInjectorAndDoEMFRegistration() {
		XbaseBundleSpaceStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}

	public Injector createInjector() {
		return Guice
				.createInjector(new UISemanticsGrammarBundleSpaceRuntimeModule());
	}
}
