/*
 * generated by Xtext
 */
package org.lunifera.ecview.uisemantics;

import org.lunifera.ecview.uisemantics.naming.QualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class UISemanticsGrammarRuntimeModule extends
		org.lunifera.ecview.uisemantics.AbstractUISemanticsGrammarRuntimeModule {

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return QualifiedNameProvider.class;
	}

}
