/*
* generated by Xtext
*/
package org.lunifera.ecview.uisemantics;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UISemanticsGrammarStandaloneSetup extends UISemanticsGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new UISemanticsGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

