/**
 * generated by Xtext
 */
package org.lunifera.ecview.uisemantics.validation;

import org.lunifera.ecview.uisemantics.validation.AbstractUISemanticsGrammarValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class UISemanticsGrammarValidator extends AbstractUISemanticsGrammarValidator {
}
